---
name: CD
on:
  workflow_dispatch:
  release:
    types: [published]
permissions:
  contents: read
jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    name: Publish on PyPI
    permissions:
      id-token: write  # IMPORTANT: Mandatory for Trusted Publishing (gh-action-pypi-publish)
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment:
      name: release
      url: https://pypi.org/project/asgi-user-agents/${{ github.ref_name }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Hatch
        uses: pypa/hatch@install
      - name: Build
        run: hatch build --clean
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
